image: docker-registry.locaweb.com.br/stretch/elixir-dev:1.9

variables:
  MIX_ENV: test

stages:
  - test
  - quality

.deps: &deps
  before_script:
    - mix do local.hex --force, local.rebar --force
    - mix deps.get

.cache: &cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - deps
    - _build

test:
  <<: *deps
  cache:
    <<: *cache
    policy: pull-push
  stage: test
  script:
    - mix test --trace --cover

credo:
  <<: *deps
  cache:
    <<: *cache
    policy: pull
  stage: quality
  script:
    - mix credo --strict

format:
  <<: *deps
  cache:
    <<: *cache
    policy: pull
  stage: quality
  script:
    - mix format --check-formatted
