image: docker-registry.locaweb.com.br/stretch/elixir-dev:1.9

stages:
  - test
  - quality

.deps: &deps
  before_script:
    - mix do local.hex --force, local.rebar --force
    - mix hex.info
    - mix deps.get

.cache: &cache
  cache:
    paths:
      - deps
      - _build

test:
  <<: *deps
  <<: *cache
  stage: test
  script:
    - mix test --trace --cover

credo:
  <<: *deps
  <<: *cache
  stage: quality
  script:
    - mix credo --strict

format:
  <<: *deps
  <<: *cache
  stage: quality
  script:
    - mix format --check-formatted
